//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2022. 04. 28. 14:52:55
namespace ODataService.Database
{
    
    /// <summary>
    /// There are no comments for ODataServiceService in the schema.
    /// </summary>
    public partial class ODataServiceService : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ODataServiceService object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ODataServiceService(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for OrderLine in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<OrderLine> OrderLine
        {
            get
            {
                if ((this._OrderLine == null))
                {
                    this._OrderLine = base.CreateQuery<OrderLine>("OrderLine");
                }
                return this._OrderLine;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<OrderLine> _OrderLine;
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Customer> Customer
        {
            get
            {
                if ((this._Customer == null))
                {
                    this._Customer = base.CreateQuery<Customer>("Customer");
                }
                return this._Customer;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Customer> _Customer;
        /// <summary>
        /// There are no comments for Pizza in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Pizza> Pizza
        {
            get
            {
                if ((this._Pizza == null))
                {
                    this._Pizza = base.CreateQuery<Pizza>("Pizza");
                }
                return this._Pizza;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Pizza> _Pizza;
        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Order> Order
        {
            get
            {
                if ((this._Order == null))
                {
                    this._Order = base.CreateQuery<Order>("Order");
                }
                return this._Order;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Order> _Order;
        /// <summary>
        /// There are no comments for Size in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Size> Size
        {
            get
            {
                if ((this._Size == null))
                {
                    this._Size = base.CreateQuery<Size>("Size");
                }
                return this._Size;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Size> _Size;
        /// <summary>
        /// There are no comments for Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Address> Address
        {
            get
            {
                if ((this._Address == null))
                {
                    this._Address = base.CreateQuery<Address>("Address");
                }
                return this._Address;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Address> _Address;
        /// <summary>
        /// There are no comments for OrderLine in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOrderLine(OrderLine orderLine)
        {
            base.AddObject("OrderLine", orderLine);
        }
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCustomer(Customer customer)
        {
            base.AddObject("Customer", customer);
        }
        /// <summary>
        /// There are no comments for Pizza in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPizza(Pizza pizza)
        {
            base.AddObject("Pizza", pizza);
        }
        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOrder(Order order)
        {
            base.AddObject("Order", order);
        }
        /// <summary>
        /// There are no comments for Size in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSize(Size size)
        {
            base.AddObject("Size", size);
        }
        /// <summary>
        /// There are no comments for Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAddress(Address address)
        {
            base.AddObject("Address", address);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"ODataService.Database\" xmlns=\"http://schemas.microsoft.com/ado/2009/1" +
                "1/edm\"><EntityType Name=\"OrderLine\"><Key><PropertyRef Name=\"Oid\" /></Key><Proper" +
                "ty Name=\"Oid\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Price\" Type=\"E" +
                "dm.Decimal\" /><Property Name=\"Qty\" Type=\"Edm.Int64\" /><NavigationProperty Name=\"" +
                "Order\" Relationship=\"ODataService.Database.OrderLine_Order_Order_OrderLines\" ToR" +
                "ole=\"Order_OrderLines\" FromRole=\"OrderLine_Order\" /><NavigationProperty Name=\"Pi" +
                "zza\" Relationship=\"ODataService.Database.OrderLine_Pizza\" ToRole=\"Pizza\" FromRol" +
                "e=\"OrderLine\" /></EntityType><EntityType Name=\"Customer\"><Key><PropertyRef Name=" +
                "\"Oid\" /></Key><Property Name=\"Oid\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property" +
                " Name=\"Name\" Type=\"Edm.String\" /><Property Name=\"Phone\" Type=\"Edm.String\" /><Nav" +
                "igationProperty Name=\"Orders\" Relationship=\"ODataService.Database.Customer_Order" +
                "s_Order_Customer\" ToRole=\"Order_Customer\" FromRole=\"Customer_Orders\" /><Navigati" +
                "onProperty Name=\"Addresses\" Relationship=\"ODataService.Database.Customer_Address" +
                "es_Address_Customer\" ToRole=\"Address_Customer\" FromRole=\"Customer_Addresses\" /><" +
                "/EntityType><EntityType Name=\"Pizza\"><Key><PropertyRef Name=\"Oid\" /></Key><Prope" +
                "rty Name=\"Oid\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"E" +
                "dm.String\" /><Property Name=\"UnitPrice\" Type=\"Edm.Decimal\" /></EntityType><Entit" +
                "yType Name=\"Order\"><Key><PropertyRef Name=\"Oid\" /></Key><Property Name=\"Oid\" Typ" +
                "e=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Description\" Type=\"Edm.String\" " +
                "/><NavigationProperty Name=\"Customer\" Relationship=\"ODataService.Database.Custom" +
                "er_Orders_Order_Customer\" ToRole=\"Customer_Orders\" FromRole=\"Order_Customer\" /><" +
                "NavigationProperty Name=\"Address\" Relationship=\"ODataService.Database.Order_Addr" +
                "ess\" ToRole=\"Address\" FromRole=\"Order\" /><NavigationProperty Name=\"OrderLines\" R" +
                "elationship=\"ODataService.Database.OrderLine_Order_Order_OrderLines\" ToRole=\"Ord" +
                "erLine_Order\" FromRole=\"Order_OrderLines\" /></EntityType><EntityType Name=\"Size\"" +
                "><Key><PropertyRef Name=\"Oid\" /></Key><Property Name=\"Oid\" Type=\"Edm.Int32\" Null" +
                "able=\"false\" /><Property Name=\"Diameter\" Type=\"Edm.Int32\" /></EntityType><Entity" +
                "Type Name=\"Address\"><Key><PropertyRef Name=\"Oid\" /></Key><Property Name=\"Oid\" Ty" +
                "pe=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"City\" Type=\"Edm.String\" /><Pro" +
                "perty Name=\"Street\" Type=\"Edm.String\" /><Property Name=\"StreetType\" Type=\"Edm.St" +
                "ring\" /><Property Name=\"HouseNumber\" Type=\"Edm.String\" /><NavigationProperty Nam" +
                "e=\"Customer\" Relationship=\"ODataService.Database.Customer_Addresses_Address_Cust" +
                "omer\" ToRole=\"Customer_Addresses\" FromRole=\"Address_Customer\" /></EntityType><As" +
                "sociation Name=\"OrderLine_Order_Order_OrderLines\"><End Type=\"ODataService.Databa" +
                "se.Order\" Role=\"Order_OrderLines\" Multiplicity=\"0..1\" /><End Type=\"ODataService." +
                "Database.OrderLine\" Role=\"OrderLine_Order\" Multiplicity=\"*\" /></Association><Ass" +
                "ociation Name=\"OrderLine_Pizza\"><End Type=\"ODataService.Database.Pizza\" Role=\"Pi" +
                "zza\" Multiplicity=\"0..1\" /><End Type=\"ODataService.Database.OrderLine\" Role=\"Ord" +
                "erLine\" Multiplicity=\"*\" /></Association><Association Name=\"Customer_Orders_Orde" +
                "r_Customer\"><End Type=\"ODataService.Database.Order\" Role=\"Order_Customer\" Multip" +
                "licity=\"*\" /><End Type=\"ODataService.Database.Customer\" Role=\"Customer_Orders\" M" +
                "ultiplicity=\"0..1\" /></Association><Association Name=\"Customer_Addresses_Address" +
                "_Customer\"><End Type=\"ODataService.Database.Address\" Role=\"Address_Customer\" Mul" +
                "tiplicity=\"*\" /><End Type=\"ODataService.Database.Customer\" Role=\"Customer_Addres" +
                "ses\" Multiplicity=\"0..1\" /></Association><Association Name=\"Order_Address\"><End " +
                "Type=\"ODataService.Database.Order\" Role=\"Order\" Multiplicity=\"*\" /><End Type=\"OD" +
                "ataService.Database.Address\" Role=\"Address\" Multiplicity=\"0..1\" /></Association>" +
                "<EntityContainer Name=\"ODataServiceService\" m:IsDefaultEntityContainer=\"true\"><E" +
                "ntitySet Name=\"OrderLine\" EntityType=\"ODataService.Database.OrderLine\" /><Entity" +
                "Set Name=\"Customer\" EntityType=\"ODataService.Database.Customer\" /><EntitySet Nam" +
                "e=\"Pizza\" EntityType=\"ODataService.Database.Pizza\" /><EntitySet Name=\"Order\" Ent" +
                "ityType=\"ODataService.Database.Order\" /><EntitySet Name=\"Size\" EntityType=\"OData" +
                "Service.Database.Size\" /><EntitySet Name=\"Address\" EntityType=\"ODataService.Data" +
                "base.Address\" /><FunctionImport Name=\"OperationName\" m:HttpMethod=\"GET\"><Paramet" +
                "er Name=\"arg1\" Type=\"Edm.String\" /></FunctionImport><FunctionImport Name=\"GetPiz" +
                "za\" ReturnType=\"ODataService.Database.Pizza\" EntitySet=\"Pizza\" m:HttpMethod=\"GET" +
                "\"><Parameter Name=\"name\" Type=\"Edm.String\" /></FunctionImport><FunctionImport Na" +
                "me=\"ObjektumVissza\" ReturnType=\"Edm.Boolean\" IsBindable=\"true\" m:IsAlwaysBindabl" +
                "e=\"true\"><Parameter Name=\"entity\" Type=\"ODataService.Database.Pizza\" /></Functio" +
                "nImport><AssociationSet Name=\"OrderLine_Order_Order\" Association=\"ODataService.D" +
                "atabase.OrderLine_Order_Order_OrderLines\"><End Role=\"OrderLine_Order\" EntitySet=" +
                "\"OrderLine\" /><End Role=\"Order_OrderLines\" EntitySet=\"Order\" /></AssociationSet>" +
                "<AssociationSet Name=\"OrderLine_Pizza_Pizza\" Association=\"ODataService.Database." +
                "OrderLine_Pizza\"><End Role=\"OrderLine\" EntitySet=\"OrderLine\" /><End Role=\"Pizza\"" +
                " EntitySet=\"Pizza\" /></AssociationSet><AssociationSet Name=\"Order_Customer_Custo" +
                "mer\" Association=\"ODataService.Database.Customer_Orders_Order_Customer\"><End Rol" +
                "e=\"Customer_Orders\" EntitySet=\"Customer\" /><End Role=\"Order_Customer\" EntitySet=" +
                "\"Order\" /></AssociationSet><AssociationSet Name=\"Address_Customer_Customer\" Asso" +
                "ciation=\"ODataService.Database.Customer_Addresses_Address_Customer\"><End Role=\"C" +
                "ustomer_Addresses\" EntitySet=\"Customer\" /><End Role=\"Address_Customer\" EntitySet" +
                "=\"Address\" /></AssociationSet><AssociationSet Name=\"Order_Address_Address\" Assoc" +
                "iation=\"ODataService.Database.Order_Address\"><End Role=\"Order\" EntitySet=\"Order\"" +
                " /><End Role=\"Address\" EntitySet=\"Address\" /></AssociationSet></EntityContainer>" +
                "<Annotations Target=\"ODataService.Database.Order/Description\"><ValueAnnotation T" +
                "erm=\"Org.OData.Validation.V1.Size\" Int=\"100\" /></Annotations><Annotations Target" +
                "=\"ODataService.Database.Customer/Name\"><ValueAnnotation Term=\"Org.OData.Validati" +
                "on.V1.Size\" Int=\"100\" /></Annotations><Annotations Target=\"ODataService.Database" +
                ".Customer/Phone\"><ValueAnnotation Term=\"Org.OData.Validation.V1.Size\" Int=\"100\" " +
                "/></Annotations><Annotations Target=\"ODataService.Database.Pizza/Name\"><ValueAnn" +
                "otation Term=\"Org.OData.Validation.V1.Size\" Int=\"100\" /></Annotations><Annotatio" +
                "ns Target=\"ODataService.Database.Address/City\"><ValueAnnotation Term=\"Org.OData." +
                "Validation.V1.Size\" Int=\"100\" /></Annotations><Annotations Target=\"ODataService." +
                "Database.Address/Street\"><ValueAnnotation Term=\"Org.OData.Validation.V1.Size\" In" +
                "t=\"100\" /></Annotations><Annotations Target=\"ODataService.Database.Address/Stree" +
                "tType\"><ValueAnnotation Term=\"Org.OData.Validation.V1.Size\" Int=\"100\" /></Annota" +
                "tions><Annotations Target=\"ODataService.Database.Address/HouseNumber\"><ValueAnno" +
                "tation Term=\"Org.OData.Validation.V1.Size\" Int=\"100\" /></Annotations></Schema></" +
                "edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for ODataService.Database.OrderLine in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Oid
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Oid")]
    public partial class OrderLine
    {
        /// <summary>
        /// Create a new OrderLine object.
        /// </summary>
        /// <param name="oid">Initial value of Oid.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static OrderLine CreateOrderLine(int oid)
        {
            OrderLine orderLine = new OrderLine();
            orderLine.Oid = oid;
            return orderLine;
        }
        /// <summary>
        /// There are no comments for Property Oid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Oid
        {
            get
            {
                return this._Oid;
            }
            set
            {
                this.OnOidChanging(value);
                this._Oid = value;
                this.OnOidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Oid;
        partial void OnOidChanging(int value);
        partial void OnOidChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this._Price = value;
                this.OnPriceChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Price;
        partial void OnPriceChanging(global::System.Nullable<decimal> value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Property Qty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> Qty
        {
            get
            {
                return this._Qty;
            }
            set
            {
                this.OnQtyChanging(value);
                this._Qty = value;
                this.OnQtyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _Qty;
        partial void OnQtyChanging(global::System.Nullable<long> value);
        partial void OnQtyChanged();
        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Order Order
        {
            get
            {
                return this._Order;
            }
            set
            {
                this._Order = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Order _Order;
        /// <summary>
        /// There are no comments for Pizza in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Pizza Pizza
        {
            get
            {
                return this._Pizza;
            }
            set
            {
                this._Pizza = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Pizza _Pizza;
    }
    /// <summary>
    /// There are no comments for ODataService.Database.Customer in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Oid
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Oid")]
    public partial class Customer
    {
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="oid">Initial value of Oid.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Customer CreateCustomer(int oid)
        {
            Customer customer = new Customer();
            customer.Oid = oid;
            return customer;
        }
        /// <summary>
        /// There are no comments for Property Oid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Oid
        {
            get
            {
                return this._Oid;
            }
            set
            {
                this.OnOidChanging(value);
                this._Oid = value;
                this.OnOidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Oid;
        partial void OnOidChanging(int value);
        partial void OnOidChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this._Phone = value;
                this.OnPhoneChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Order> Orders
        {
            get
            {
                return this._Orders;
            }
            set
            {
                if ((value != null))
                {
                    this._Orders = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Order> _Orders = new global::System.Collections.ObjectModel.Collection<Order>();
        /// <summary>
        /// There are no comments for Addresses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Address> Addresses
        {
            get
            {
                return this._Addresses;
            }
            set
            {
                if ((value != null))
                {
                    this._Addresses = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Address> _Addresses = new global::System.Collections.ObjectModel.Collection<Address>();
    }
    /// <summary>
    /// There are no comments for ODataService.Database.Pizza in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Oid
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Oid")]
    public partial class Pizza
    {
        /// <summary>
        /// Create a new Pizza object.
        /// </summary>
        /// <param name="oid">Initial value of Oid.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Pizza CreatePizza(int oid)
        {
            Pizza pizza = new Pizza();
            pizza.Oid = oid;
            return pizza;
        }
        /// <summary>
        /// There are no comments for Property Oid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Oid
        {
            get
            {
                return this._Oid;
            }
            set
            {
                this.OnOidChanging(value);
                this._Oid = value;
                this.OnOidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Oid;
        partial void OnOidChanging(int value);
        partial void OnOidChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property UnitPrice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> UnitPrice
        {
            get
            {
                return this._UnitPrice;
            }
            set
            {
                this.OnUnitPriceChanging(value);
                this._UnitPrice = value;
                this.OnUnitPriceChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _UnitPrice;
        partial void OnUnitPriceChanging(global::System.Nullable<decimal> value);
        partial void OnUnitPriceChanged();
    }
    /// <summary>
    /// There are no comments for ODataService.Database.Order in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Oid
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Oid")]
    public partial class Order
    {
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="oid">Initial value of Oid.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Order CreateOrder(int oid)
        {
            Order order = new Order();
            order.Oid = oid;
            return order;
        }
        /// <summary>
        /// There are no comments for Property Oid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Oid
        {
            get
            {
                return this._Oid;
            }
            set
            {
                this.OnOidChanging(value);
                this._Oid = value;
                this.OnOidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Oid;
        partial void OnOidChanging(int value);
        partial void OnOidChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Customer Customer
        {
            get
            {
                return this._Customer;
            }
            set
            {
                this._Customer = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Customer _Customer;
        /// <summary>
        /// There are no comments for Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Address Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this._Address = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Address _Address;
        /// <summary>
        /// There are no comments for OrderLines in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<OrderLine> OrderLines
        {
            get
            {
                return this._OrderLines;
            }
            set
            {
                if ((value != null))
                {
                    this._OrderLines = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<OrderLine> _OrderLines = new global::System.Collections.ObjectModel.Collection<OrderLine>();
    }
    /// <summary>
    /// There are no comments for ODataService.Database.Size in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Oid
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Oid")]
    public partial class Size
    {
        /// <summary>
        /// Create a new Size object.
        /// </summary>
        /// <param name="oid">Initial value of Oid.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Size CreateSize(int oid)
        {
            Size size = new Size();
            size.Oid = oid;
            return size;
        }
        /// <summary>
        /// There are no comments for Property Oid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Oid
        {
            get
            {
                return this._Oid;
            }
            set
            {
                this.OnOidChanging(value);
                this._Oid = value;
                this.OnOidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Oid;
        partial void OnOidChanging(int value);
        partial void OnOidChanged();
        /// <summary>
        /// There are no comments for Property Diameter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Diameter
        {
            get
            {
                return this._Diameter;
            }
            set
            {
                this.OnDiameterChanging(value);
                this._Diameter = value;
                this.OnDiameterChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Diameter;
        partial void OnDiameterChanging(global::System.Nullable<int> value);
        partial void OnDiameterChanged();
    }
    /// <summary>
    /// There are no comments for ODataService.Database.Address in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Oid
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Oid")]
    public partial class Address
    {
        /// <summary>
        /// Create a new Address object.
        /// </summary>
        /// <param name="oid">Initial value of Oid.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Address CreateAddress(int oid)
        {
            Address address = new Address();
            address.Oid = oid;
            return address;
        }
        /// <summary>
        /// There are no comments for Property Oid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Oid
        {
            get
            {
                return this._Oid;
            }
            set
            {
                this.OnOidChanging(value);
                this._Oid = value;
                this.OnOidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Oid;
        partial void OnOidChanging(int value);
        partial void OnOidChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property Street in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Street
        {
            get
            {
                return this._Street;
            }
            set
            {
                this.OnStreetChanging(value);
                this._Street = value;
                this.OnStreetChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Street;
        partial void OnStreetChanging(string value);
        partial void OnStreetChanged();
        /// <summary>
        /// There are no comments for Property StreetType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string StreetType
        {
            get
            {
                return this._StreetType;
            }
            set
            {
                this.OnStreetTypeChanging(value);
                this._StreetType = value;
                this.OnStreetTypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _StreetType;
        partial void OnStreetTypeChanging(string value);
        partial void OnStreetTypeChanged();
        /// <summary>
        /// There are no comments for Property HouseNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string HouseNumber
        {
            get
            {
                return this._HouseNumber;
            }
            set
            {
                this.OnHouseNumberChanging(value);
                this._HouseNumber = value;
                this.OnHouseNumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _HouseNumber;
        partial void OnHouseNumberChanging(string value);
        partial void OnHouseNumberChanged();
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Customer Customer
        {
            get
            {
                return this._Customer;
            }
            set
            {
                this._Customer = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Customer _Customer;
    }
}
